### ISSUE TITLE
Lier les sujets github des streams aux projet github

### ISSUE THREAD

**Issue by billmetangmo** [mongulu-cm/lobembe#13]
Pour recevoir les notifications de toutes les branches lorsqu'on y push.
https://zulip.com/integrations/doc/github

**Comment by billmetangmo** [comment]
/remind @ngnnpgn about the task saturday at 09:00 AM

**Comment by billmetangmo** [comment]
/remind me about it in 1 minute

**Comment by ngnnpgn** [comment]
Comment to test if the _comment issue_ notification will be trigger on zulip.
