### ISSUE TITLE
Post-ops: Monitor uptime blog.mongulu.cm, pg.monulu.cm, lobembe.mongulu.cm and notifications when failed

### ISSUE THREAD

**Issue by billmetangmo** [mongulu-cm/lobembe#54]
Choose a tool from https://github.com/topics/uptime . Perfered https://github.com/upptime/upptime as totally managed by Github

**Comment by billmetangmo** [comment]
If applications are based on multiple services like posthog when web can be online but plugin is off ( this arrived) , check if posthog fournishes something to check the status of it's service like in web /instance/status

**Comment by billmetangmo** [comment]
@fabiolatagne97 use this https://github.com/tgymnich/fork-sync so that the fork will always be up to date

**Comment by billmetangmo** [comment]
Also metabase.mongulu.cm

**Comment by billmetangmo** [comment]
https://github.com/mongulu-cm/uptime

**Comment by fabiolatagne97** [comment]
done  see it on 👍 https://mongulu-cm.github.io/uptime/

**Comment by fabiolatagne97** [comment]
done see it on 👍 https://mongulu-cm.github.io/uptime/
