### ISSUE TITLE
Have our kubernetes cluster in the collective

### ISSUE THREAD

**Issue by billmetangmo** [mongulu-cm/lobembe#68]
Running using k3s for example and a collective member oracle instances.

**Comment by billmetangmo** [comment]
- Airbyte

**Comment by billmetangmo** [comment]
cluster créer avec une instance

**Comment by tsafacjo** [comment]
@billmetangmo could we talk about this user story  tomorrow ?

**Comment by billmetangmo** [comment]
Yes

**Comment by billmetangmo** [comment]
@tsafacjo  
- crée une instance oracle cloud ARM au mois 1 coeur, 6 Go https://www.loom.com/share/e9035635c55143a8acc0ff8716921c30
- déployer une instance sur terraform cloud https://github.com/r0b2g1t/k3s-cluster-on-oracle-cloud-infrastructure
- essayer de déployer dessus une marhine veirtuelle x86-84 en utilisant https://www.proxmox.com/en/

**Comment by tsafacjo** [comment]
It looks like if there no that much free instance.
I change the region too but not better.

![Image](https://github.com/mongulu-cm/lobembe/assets/26392278/be892f27-eefa-4300-9b0c-477f05b87d0f)

**Comment by billmetangmo** [comment]
Ah, i got the same issue last week when trying to create instance before assigning to you this task.
Seems that there is something weird with oracle these days.
I just checked for wokaround on the web and found:
- https://www.reddit.com/r/oraclecloud/comments/zf0tje/out_of_capacity_for_shape_vmstandarda1flex/
- https://www.youtube.com/watch?v=Xto9zROBwqY

from my search https://www.google.com/search?q=oracle+out+of+capacity+for+shape

**Comment by tsafacjo** [comment]
this script is still ongoing :

**setInterval(function() {
var v = document.querySelector(".oui-savant__Panel--Footer .oui-button.oui-button-primary");
if (v && v.textContent == "Create") {
    v.click();
    console.log("clicked");
} else
    console.log("no button");
}, 30000);**

**Comment by billmetangmo** [comment]
L'installation de proxmox sur ARM est très compliqué 
Il y a un projet pimox mais il macrge que sur rasberry pi.
Etant donné que le hardware ne supporte pas de virtualisation, on peut regarder du côté de qemu mais ça failed avec l'erreur error: can't find command \grub_platform'`

Il s'agit donc d'une autre issue que celle-ci.
Nous considérons donc qu'on a pu déployer un cluster avec un noeud.
